name: Deploy Flutter Web App to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0' # Remplacez par la version de Flutter que vous utilisez

      - name: Install dependencies
        working-directory: ./Front
        run: flutter pub get

      - name: Build Flutter Web
        working-directory: ./Front
        run: flutter build web

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./Front/build/web s3://your-bucket-name --delete
